### ISSUE TITLE
Cannot compile after updating to 130b0d4 from 6a74584

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#153]
We integrate into Xcode by dragging the .xcodeproj file into XCode into a group we named TestFrameworks. This is how we've always done it.  Today after updating to 130b0d4 we can no longer compile. 
We import into a given test case using: 
```
#import <OHHTTPStubs/OHHTTPStubs.h>
```
If we have a line of code in a stub that uses responseWithJSONObject the compiler complains with, "No Known class method for selector 'responseWithJSONObject:statusCode:headers"
```
return [[OHHTTPStubsResponse responseWithJSONObject:@{}
												 statusCode:200
												headers:@{@"Content-Type":@"text/json"}]
```

Furthermore, in other stubs I've been using responseWithFileAtPath:OHPathForFile
we see "Implicit declaration of function 'OHPathForFile is invalid in C99.
```
    return [[OHHTTPStubsResponse responseWithFileAtPath:OHPathForFile(@"somestuff.json", self.class)
												 statusCode:200
												headers:@{@"Content-Type":@"text/json"}]
````

My code still matches the examples you've posted so I don't suspect that my existing code is wrong.
What then could be the cause? Perhaps my integration?
Please advise....

Thanks in advance

**Comment by samirGuerdah** [comment]
Hello,

Try this : ```  #import <OHHTTPStubs/OHHTTPStubsResponse+JSON.h> ```

**Comment by mikelupo** [comment]
Thank you.
That helps with the first issue.

The second issue, 
return [[OHHTTPStubsResponse responseWithFileAtPath:OHPathForFile
is not solved.

**Comment by mikelupo** [comment]
I got it.  
#import <OHHTTPStubs/OHPathHelpers.h>

Thanks again @samirGuerdah for your answer.

**Comment by mikelupo** [comment]
Trying again.
#import <OHHTTPStubs/OHPathHelpers.h>
