### ISSUE TITLE
OHHTTPStubs doesn't build on Xcode 7.1 using frameworks

### ISSUE THREAD

**Issue by tuzonghua** [AliSoftware/OHHTTPStubs#132]
Running Xcode 7.1 and CocoaPods 0.39.0 with the `use_frameworks!` directive. Getting the following error:

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "<project path>/Pods/Target Support Files/OHHTTPStubs/OHHTTPStubs-umbrella.h"
        ^
<project path>/Pods/Target Support Files/OHHTTPStubs/OHHTTPStubs-umbrella.h:4:9: note: in file included from <project path>/Pods/Target Support Files/OHHTTPStubs/OHHTTPStubs-umbrella.h:4:
#import "OHHTTPStubs.h"
        ^
<project path>/Pods/OHHTTPStubs/OHHTTPStubs/Sources/OHHTTPStubs.h:32:9: error: include of non-modular header inside framework module 'OHHTTPStubs.OHHTTPStubs'
#import <OHHTTPStubs/OHHTTPStubsResponse.h>
        ^
<unknown>:0: error: could not build Objective-C module 'OHHTTPStubs'
```

Tried setting the `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` setting to `YES` but that still didn't work. It was working previously with the last release of Xcode, so I wonder if something changed in 7.1 that caused it to break.

**Comment by AliSoftware** [comment]
What version of `OHHTTPStubs` did you pull in your `Podfile`? Is it using [the latest `4.4.0`](https://github.com/AliSoftware/OHHTTPStubs/releases/tag/4.4.0) — which should have fixed #127 and thus fix this kind of issues?

**Comment by tuzonghua** [comment]
Ah, my bad. Closing.
